### ISSUE TITLE
Docker instructions

### ISSUE THREAD

**Issue by royackerman** [OSS-team-zulu/Zulu#12]
Super informative README and awesome project..

Might be useful to get Docker the docker-compose.yml / instructions how to build it.

Good luck!

**Comment by jherskow** [comment]
Very valid, thanks for the feedback.

This PR: https://github.com/OSS-team-zulu/Zulu/pull/19
 includes a rewrite of the documentations, as well as clarified instructions so that contributors can work separately in the FE and BE without dealing with docker.
