### ISSUE TITLE
Add support for "Full Name" in the Profile page

### ISSUE THREAD

**Issue by nvgoldin** [OSS-team-zulu/Zulu#26]
"full_name" is supported by the Backend, but the ReactJS part doesn't send it, see this pic:
![image](https://user-images.githubusercontent.com/13018704/86535451-16f47b80-bee9-11ea-9596-e56141d6a8c6.png)

Adding support should be fairly trivial, follow these steps:
1. Modify the [registration form component](https://github.com/OSS-team-zulu/Zulu/blob/master/frontend/zulu/src/components/Login/register.component.js) to include the new "Full Name" field:

https://github.com/OSS-team-zulu/Zulu/blob/4b39d0a6118d43c272ac0fa191b08233b7b8b675/frontend/zulu/src/components/Login/register.component.js#L39-L64

  * Add validation function `vfullname` and update the state/div where needed.
  * Make sure to update the `AuthService.createUser` to include it too:
https://github.com/OSS-team-zulu/Zulu/blob/4b39d0a6118d43c272ac0fa191b08233b7b8b675/frontend/zulu/src/components/Login/register.component.js#L95-L98

2. Finally - test that you can register with fullname, and Profile works.

**Comment by royackerman** [comment]
Did it
https://github.com/OSS-team-zulu/Zulu/pull/32/commits/6bf8d7eb3edad849ebb3edd3c89d8405a78b2972
